language: python
python: 3.7
sudo: false
install: "pip install -r maintenance/requirements.txt"
script: "python maintenance/github-crawler.py"
deploy:
  provider: script
  script: sh $TRAVIS_BUILD_DIR/.travis/push.sh
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master

