language: python
python: 3.6
sudo: false
install: "pip install -r maintenance/requirements.txt"
script: "python maintenance/github-crawler.py"
after_success:
  - .travis/push.sh
env:
  global:
    secure: 15256b24a9a72adab6a42cc2dc4e46c180234685
